# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: swift
osx_image: xcode8
env:
  global:
    - PROJECT=Tests/LeafTests.xcodeproj
    - SCHEME=LeafTests
    - DESTINATION="OS=10.0,name=iPhone 7"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -sdk iphonesimulator test

#- set -o pipefail && xcodebuild test -workspace Example/Leaf.xcworkspace -scheme Leaf-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#  - pod lib lint
